version: '1'
services:
  frontend:
    build: 
      context: ./frontend
    image: dilansriyantha/soil-sense-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    image: dilansriyantha/soil-sense-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=soilsensedb
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=soilsensedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"

volumes:
  db_data: